kakao.client-id=${CLIENT_ID}
kakao.redirect-uri=${REDIRECT_URI}
kakao.auth-url=https://kauth.kakao.com/oauth/authorize
kakao.token-url=https://kauth.kakao.com/oauth/token
kakao.user-info-url=https://kapi.kakao.com/v2/user/me

kakaopay.ready-url=https://open-api.kakaopay.com/online/v1/payment/ready
kakaopay.secret-key= ${SECRET_KEY}
kakaopay.approve-url=https://open-api.kakaopay.com/online/v1/payment/approve